name: desafio_campominado
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mobx:
  flutter_mobx:
  get_it:
  flutter_icons:
  intl:
  vibration:
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  flutter_speed_dial: ^1.2.5
  esys_flutter_share:
  flutter_staggered_grid_view: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen:
  build_runner:

flutter:
  uses-material-design: true